### ISSUE TITLE
Ask for some sources of your recent great job .

### ISSUE THREAD

**Issue by NHZlX** [untrix/im2latex#12]
hi Singh,  the result you offered is amazing and exciting! Would you mind providing your training parameter files? I want to take a quick look at the test results. Many thanks!

**Comment by untrix** [comment]
Hi NHZIX,
    Thank you for the compliment! All training parameters are contained within the source code. The files src/run.py and src/model/hyper_params.py . If you follow the directions on the main page you should be able to reproduce the results. Some test results are put up on the website: https://untrix.github.io/i2l. Hope that helps.
