### ISSUE TITLE
Image augmentation

### ISSUE THREAD

**Issue by bezigon** [untrix/im2latex#14]
I write simple augmentation pipeline for mimicking near real photo of mathematical formulas.
I think, I have some potential problems:

Augmented data. It's grows exponentially with every filter I used. I have several filters (augmentation operations), such as:

- Radius
- Distortion
- Perspective transforms
- Simple Blur
- Motion Blur
- Drop shadows

And question (or optimization process):
Can the image generator used with augmenting the data without saving them? Or there may be problems with the output size of augmented images (they can change it's size) and CNN->LSTM requires the shapes to be defined?

**Comment by untrix** [comment]
The model expects all images to be smaller than or equal to the max size (max-size is recorded along with the dataset in data_props.pkl). The data-reader code pads smaller images to the max-size. Therefore if you ensure that your modified images are less than or equal to the max size (height, width) then you should be okay. You could actually invoke your augmentation pipeline code from data-reader - for e.g. you could create your own the ImageProcessor class (perhaps a subclass of ImageProcessor3_BW).
