### ISSUE TITLE
VGG (transfer learning)

### ISSUE THREAD

**Issue by bezigon** [untrix/im2latex#15]
I saw that VGG (transfer learning) is used, but seems not working. Why? Because of shape (224x224) or other reasons, such as VGG is not intended for use with OCR/rendered latex formulas?

**Comment by untrix** [comment]
Hi @bezigon,
    I had started with VGG transfer learning, but abandoned that approach because I got much better results with a custom CNN. I think the main reason for that (as I mention in my paper) is that VGG was trained on natural images whereas my dataset is math formulas (black ink on white background). Also, the task that VGG was trained on is completely different than the task here. That's why there is a lot of unused code in data-reader as well as within the model folder (because I tried several approaches).
