### ISSUE TITLE
where are the pretrained model weights

### ISSUE THREAD

**Issue by vyaslkv** [untrix/im2latex#20]

**Comment by untrix** [comment]
Sorry, saw this only now. I will upload pre-trained weights in a couple of weeks. Won't be useful to you anymore I suppose, but perhaps for others.

**Comment by bilalsattar** [comment]
@untrix any update on this issue.

**Comment by untrix** [comment]
Sorry for the delay. Since the original comment is from a year back, I wasn't sure if there was still any interest. Will upload the weights soon. How urgent is your request though?

**Comment by bilalsattar** [comment]
Actually its quite urgent. I can train myself but it would be better if I get the weights or atleast the preprocessed data.
Thanks in advance.

**Comment by huytuong010101** [comment]
@untrix  can u share with me your pretrained model? My computer is not good to train this model but I really need this model to do my education project in my school. This is my email: huytuong010101@gmail.com

**Comment by untrix** [comment]
@bilalsattar @huytuong010101 The pertained model checkpoints are now available on the website for download (https://untrix.github.io/i2l). These are checkpoints of the original 2-GPU run, so you'll have to extract them from the checkpoint if you're training with a different # of GPUs or. The original model parameters are under hyper.pkl and also printed to training.log which are in the download.

@bilalsattar the preprocessed data can also be downloaded from the same site.
