### ISSUE TITLE
Error in running Predict.ipynb

### ISSUE THREAD

**Issue by PhenomenalOnee** [untrix/im2latex#22]
I downloaded your given weights and dataset5 which contains training_56 folder with pickle files and run predict.ipynb, but  the results on my test images were not good,
Can you explain your training preprocessing steps like cropping, thresholding

**Comment by untrix** [comment]
If your images look very different from the training set then you should fine tune the model with your dataset. Alternatively if you can resize, pad, color (black text on white background) and scale your images to match those you see here, then you should be able to get reasonably close performance. As for the exact data processing done in this project start at the 'Dataset Processing' section of the top level Readme file and then follow on to the src/preprocessing folder which has the exact preprocessing notebooks that I used. There are tons of example images on the website (and inside the paper and possibly in the repo too) that give a very good idea of what the images look like. If yours look like those, you should get very good results. Good luck.
